### ISSUE TITLE
Question about FM WebViewer Bridge?

### ISSUE THREAD

**Issue by toddgeist** [soliantconsulting/carafe#3]
Hey Guys, 

Looks very cool.

You mention docs for "FM Webveiwer Bridge". This maybe something you guys made, but thought I would ask if you guys are using 

https://github.com/geistinteractive/fm-webviewer-bridge

I don't think you are, but I am curious if others are using our project.

Thanks

Todd

**Comment by jeremiahsmall** [comment]
Yup. https://github.com/soliantconsulting/carafe/blob/master/package.json#L38

The FileMaker portion is also being done ModularFM

We've got this repo public because that's needed for integration testing, but it's still pre-release, and the repo is missing a lot of stuff, including complete documentation and the FileMaker portion. We were hoping to have it ready in the next day or so and share it with you in advance of DevCon.

We're not doing any kind of big launch, nor any DevCon topic about it. We just wanted to have it tuned up prior so that we'd be able to share and discuss. It's meant to be an additive community project.

**Comment by jeremiahsmall** [comment]
Oh, also, I'm doing the FileMaker components essentially following ModularFM standards, with the big caveat that we rely on a custom function. What's the current ModularFM thinking on those?

**Comment by toddgeist** [comment]
Sweet! 

I'll be laying out some new ideas for guidelines for ModularFileMaker standards. That will include removing the ban on custom functions.  They are just too useful, especially in combo with JSON.

Todd

**Comment by toddgeist** [comment]
I have time tomorrow afternoon. Friday is out as I will be on my way.  How about 3PM Pacific tomorrow?
